// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmMBJgb_9t5aPnnCGWo5UhZh4TPPwMdQ',
    appId: '1:55895037611:web:01a70c5e2ad26ad72ec9ee',
    messagingSenderId: '55895037611',
    projectId: 'push-notification-1e0ac',
    authDomain: 'push-notification-1e0ac.firebaseapp.com',
    storageBucket: 'push-notification-1e0ac.appspot.com',
    measurementId: 'G-5ZD6FCXWNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_nnQqosI68J5qWl1EHPnzJ7sHxSM5zY',
    appId: '1:55895037611:android:842fb07eec7737fa2ec9ee',
    messagingSenderId: '55895037611',
    projectId: 'push-notification-1e0ac',
    storageBucket: 'push-notification-1e0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DLJ3n753ixNT5rZrerAGK7YxN8vlt9c',
    appId: '1:55895037611:ios:5de1ae01f04c45292ec9ee',
    messagingSenderId: '55895037611',
    projectId: 'push-notification-1e0ac',
    storageBucket: 'push-notification-1e0ac.appspot.com',
    iosClientId: '55895037611-8m5akcrbldfkti2im4plkrtsq7hp19sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DLJ3n753ixNT5rZrerAGK7YxN8vlt9c',
    appId: '1:55895037611:ios:5de1ae01f04c45292ec9ee',
    messagingSenderId: '55895037611',
    projectId: 'push-notification-1e0ac',
    storageBucket: 'push-notification-1e0ac.appspot.com',
    iosClientId: '55895037611-8m5akcrbldfkti2im4plkrtsq7hp19sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
